import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const distDir = resolve(import.meta.dir, "../dist/ui");
const outFile = resolve(import.meta.dir, "../src/server/ui-assets.ts");

const html = readFileSync(resolve(distDir, "index.html"), "utf-8");
const js = readFileSync(resolve(distDir, "index.js"), "utf-8");
const css = readFileSync(resolve(distDir, "index.css"), "utf-8");

const output = `// This file is auto-generated by scripts/embed-ui.ts. Do not edit manually.
export const embeddedHtml = ${JSON.stringify(html)};
export const embeddedJs = ${JSON.stringify(js)};
export const embeddedCss = ${JSON.stringify(css)};
`;

writeFileSync(outFile, output);
console.log("UI assets embedded into src/server/ui-assets.ts");
